const categories = [
  {
    topic: 1,
    name: 'El Derecho',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 2,
    name: 'La Constitución Española (I)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 3,
    name: 'La Constitución Española (II)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 4,
    name: 'La Unión Europea',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 5,
    name: 'La AGE',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 6,
    name: 'Funcionarios Públicos',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 7,
    name: 'El Ministerio Del Interior',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 8,
    name: 'La DGP',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 9,
    name: 'La LO 2/86',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 10,
    name: 'Extranjería (I)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 11,
    name: 'Extranjería (II)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 12,
    name: 'Protección Internacional',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 13,
    name: 'Seguridad Privada',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 14,
    name: 'La LO 4/15',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 15,
    name: 'Protección De Infraestructuras Críticas',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 16,
    name: 'Derecho Penal General',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 17,
    name: 'Derecho Penal Especial (I)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 18,
    name: 'Derecho Penal Especial (II)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 19,
    name: 'Derecho Penal Especial (III)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 20,
    name: 'Derecho Penal Especial (IV)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 21,
    name: 'Derecho Procesal Penal',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 22,
    name: 'Estatuto De La Víctima Del Delito',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 23,
    name: 'Violencia De Género',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 24,
    name: 'PRL',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 25,
    name: 'PRL (II)',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 26,
    name: 'Protección De Datos',
    block: 'Juridicas',
    slug: 'juridicas',
  },
  {
    topic: 27,
    name: 'Derechos Humanos',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 28,
    name: 'Globalización',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 29,
    name: 'Actitudes Y Valores',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 30,
    name: 'Principios Éticos De La Sociedad Actual',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 31,
    name: 'Inmigración',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 32,
    name: 'Geografía Humana',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 33,
    name: 'La Seguridad',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 34,
    name: 'Drogodependencias',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 35,
    name: 'El Desarrollo Sostenible',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 36,
    name: 'Gramática Española',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 37,
    name: 'Ortografía Española',
    block: 'Ciencias Sociales',
    slug: 'ciencias_sociales',
  },
  {
    topic: 38,
    name: 'Fundamentos De Sistemas Operativos',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 39,
    name: 'Redes Informática',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 40,
    name: 'Inteligencia',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 41,
    name: 'Ciberdelincuencia',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 42,
    name: 'Origen De Las Armas De Fuego',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 43,
    name: 'Vehículo Prioritario',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 44,
    name: 'La Seguridad En Conducción',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
  {
    topic: 45,
    name: 'PRL En Vehículos Prioritarios',
    block: 'Tecnico Cientificas',
    slug: 'tecnico_cientificas',
  },
];

export default categories;
